defaults:
  - model_summary.yaml
  - rich_progress_bar.yaml
  - _self_

step_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints
  filename: "checkpoint-{step:06d}-steps"
  monitor: "step"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False
  save_top_k: 1
  every_n_train_steps: 10000

learning_rate_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: "step"

model_summary:
  max_depth: -1
